name: Build and Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "teamdman.ca/app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
        cache-dependency-path: teamdman.ca/app/package-lock.json
    - working-directory: teamdman.ca/app
      run: npm ci
    - working-directory: teamdman.ca/app
      run: npm run build

    - name: Deploy to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./teamdman.ca/app/build
