name: Build and Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    # paths:
    #   - "teamdman.ca/app/**"

# https://github.com/actions/starter-workflows/blob/main/pages/nuxtjs.yml
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Use Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 16.x
        cache: "npm"
        cache-dependency-path: package-lock.json
    

    - name: Setup Pages
      uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      with:
        # Automatically inject router.base in your Nuxt configuration file and set
        # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
        #
        # You may remove this line if you want to manage the configuration yourself.
        static_site_generator: sveltekit

    - name: Install dependencies
      run: npm ci
      working-directory: .
    
    - name: Run build
      run: npm run build
      working-directory: .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0