name: Deploy static files to Azure storage account

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "teamdman.ca/app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with: 
        creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - working-directory: teamdman.ca/app
      run: npm ci
    - working-directory: teamdman.ca/app
      run: npm run build
    - name: wipe
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --source '${{ secrets.STORAGE_CONTAINER_NAME }}'
    - name: upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --destination '${{ secrets.STORAGE_CONTAINER_NAME }}' --source teamdman.ca/app/build
    - name: logout
      run: az logout
      if: always()
